[workspace]
members = [
    "be", 
    "be/macros", 
    "fe",
    "be/examples/*"
]

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
refinery = { version = "0.8.16", features = ["tokio-postgres"] }