services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "basic_example"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
