[package]
name = "basic-example"
version = "0.1.0"
edition = "2024"
exclude = ["./migrations", "./db"]

[dependencies]
lan_be_frame = { path = "../../../be"}
serde = { workspace = true}
refinery = { workspace = true }

