[package]
name = "lan_be_frame"
version = "0.1.0"
edition = "2024"

[dependencies]
lan_be_frame_macros = { path = "macros" }
tokio = { version = "1.45.1", features = ["full"] }
listenfd = "1.0.2"
axum = "0.8.4"
mysql = "26.0.0"
refinery = {version = "0.8.16", features = ["mysql"]}

