[package]
name = "basic-example"
version = "0.1.0"
edition = "2024"
exclude = ["./db_docker"]

[dependencies]
lan_be_frame = { path = "../..", features = ["full"] }
refinery = { workspace = true}
serde = { workspace = true}
sea-orm = { workspace = true}

